/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anvato_android_player_hls_FFMpegTask */

#ifndef _Included_com_anvato_android_player_hls_FFMpegTask
#define _Included_com_anvato_android_player_hls_FFMpegTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anvato_android_player_hls_FFMpegTask
 * Method:    run
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_anvato_android_player_hls_FFMpegTask_play
  (JNIEnv *, jobject, jobjectArray);


JNIEXPORT void JNICALL Java_com_anvato_android_player_hls_FFMpegTask_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
